In [2]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mn42899/predictive_modelling/refs/heads/main/dataset_lm.csv')
df

,Dependent Var,Explanatory Var #1,Explanatory Var #2,Explanatory Var #3,Explanatory Var #4,Explanatory Var #5,Explanatory Var #6,Explanatory Var #7,Explanatory Var #8,Explanatory Var #9,Explanatory Var #10,Explanatory Var #11,Explanatory Var #12,Explanatory Var #13,Explanatory Var #14,Explanatory Var #15
0,56.293458,13.698667,50.639873,0,-18.568035,45.121911,11.412501,56.410757,2,-12.281132,38.996909,-3.010548,49.195073,0,-21.153143,46.919314
1,58.473431,2.714725,65.845845,1,-25.105932,47.190213,10.080280,65.383107,3,-36.763585,51.654939,4.991111,45.591729,0,-6.474403,53.383508
2,94.195330,11.618072,65.072497,0,-7.897464,52.163036,11.057301,82.812717,0,-15.733547,48.913837,-2.457696,56.608806,0,-27.903299,48.515026
3,29.074583,0.818623,45.408996,1,-18.316132,54.356714,5.029029,48.812471,1,-12.825591,45.851732,14.974177,47.362594,1,-10.064411,55.266254
4,86.035569,9.077544,73.548021,0,-19.204165,47.186807,12.128134,62.520911,2,-13.804860,47.765904,9.593982,53.700562,0,-17.546302,48.150543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,61.300432,0.338441,70.430598,0,-21.525979,50.741115,-8.050843,39.075397,3,-29.197173,57.473862,15.505202,73.280605,1,-3.602482,56.317474
418,26.309237,-1.729712,47.087996,1,-19.034807,55.242929,28.001769,76.429649,0,-21.941401,54.641620,14.295688,49.816798,1,-13.910494,52.827988
419,58.350627,18.322301,53.267835,0,-26.186201,36.702958,14.530116,51.275150,2,-20.699670,46.443687,5.708762,52.751016,1,-6.202345,52.467289
420,31.954003,0.436357,61.844132,0,-25.881961,57.106851,21.786066,68.928442,0,-23.166461,59.194840,8.365762,64.291056,1,-21.330017,50.237673
421,50.590958,-3.107425,64.590632,1,-20.303215,56.374124,4.604237,49.501005,0,-18.792745,45.594612,16.414449,66.957547,0,-15.771155,43.603802

In [3]:
df.head()

,Dependent Var,Explanatory Var #1,Explanatory Var #2,Explanatory Var #3,Explanatory Var #4,Explanatory Var #5,Explanatory Var #6,Explanatory Var #7,Explanatory Var #8,Explanatory Var #9,Explanatory Var #10,Explanatory Var #11,Explanatory Var #12,Explanatory Var #13,Explanatory Var #14,Explanatory Var #15
0,56.293458,13.698667,50.639873,0,-18.568035,45.121911,11.412501,56.410757,2,-12.281132,38.996909,-3.010548,49.195073,0,-21.153143,46.919314
1,58.473431,2.714725,65.845845,1,-25.105932,47.190213,10.080280,65.383107,3,-36.763585,51.654939,4.991111,45.591729,0,-6.474403,53.383508
2,94.195330,11.618072,65.072497,0,-7.897464,52.163036,11.057301,82.812717,0,-15.733547,48.913837,-2.457696,56.608806,0,-27.903299,48.515026
3,29.074583,0.818623,45.408996,1,-18.316132,54.356714,5.029029,48.812471,1,-12.825591,45.851732,14.974177,47.362594,1,-10.064411,55.266254
4,86.035569,9.077544,73.548021,0,-19.204165,47.186807,12.128134,62.520911,2,-13.804860,47.765904,9.593982,53.700562,0,-17.546302,48.150543

In [4]:
df.columns

Index(['Dependent Var', 'Explanatory Var #1', 'Explanatory Var #2',
       'Explanatory Var #3', 'Explanatory Var #4', 'Explanatory Var #5',
       'Explanatory Var #6', 'Explanatory Var #7', 'Explanatory Var #8',
       'Explanatory Var #9', 'Explanatory Var #10', 'Explanatory Var #11',
       'Explanatory Var #12', 'Explanatory Var #13', 'Explanatory Var #14',
       'Explanatory Var #15'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Dependent Var        422 non-null    float64
 1   Explanatory Var #1   422 non-null    float64
 2   Explanatory Var #2   422 non-null    float64
 3   Explanatory Var #3   422 non-null    int64
 4   Explanatory Var #4   422 non-null    float64
 5   Explanatory Var #5   422 non-null    float64
 6   Explanatory Var #6   422 non-null    float64
 7   Explanatory Var #7   422 non-null    float64
 8   Explanatory Var #8   422 non-null    int64
 9   Explanatory Var #9   422 non-null    float64
 10  Explanatory Var #10  422 non-null    float64
 11  Explanatory Var #11  422 non-null    float64
 12  Explanatory Var #12  422 non-null    float64
 13  Explanatory Var #13  422 non-null    int64
 14  Explanatory Var #14  422 non-null    float64
 15  Explanatory Var #15  422 non-null    float64
dtypes: float64(13), int64(3)
memory usage: 52.9 KB

In [8]:
X = df[['Explanatory Var #1', 'Explanatory Var #2',
       'Explanatory Var #3', 'Explanatory Var #4', 'Explanatory Var #5',
       'Explanatory Var #6', 'Explanatory Var #7', 'Explanatory Var #8',
       'Explanatory Var #9', 'Explanatory Var #10', 'Explanatory Var #11',
       'Explanatory Var #12', 'Explanatory Var #13', 'Explanatory Var #14',
       'Explanatory Var #15']]
y = df['Dependent Var']

In [10]:
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.5, random_state=42)

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_percentage_error

# Step 2: Run the Lasso model with alpha=1 and estimate the coefficients using the training set
lasso = Lasso(alpha=1, random_state=42)
lasso.fit(X_train, y_train)

# Get the coefficients
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lasso.coef_
})

print("Coefficients estimated by the Lasso model with alpha=1:")
print(coefficients)

# Step 3: Calculate the Mean Absolute Percentage Error using the test set
y_pred = lasso.predict(X_test)
mape = mean_absolute_percentage_error(y_test, y_pred) * 100  # Multiply by 100 to get percentage

print(f"\nMean Absolute Percentage Error (MAPE) on the test set: {mape:.2f}%")

# Step 4: Find an approximate value for alpha that minimizes the MAPE
# We'll use cross-validation to test different alpha values

from sklearn.linear_model import LassoCV

# Define a range of alpha values to test
alpha_values = np.logspace(-4, 1, 50)

# Initialize LassoCV to find the best alpha
lasso_cv = LassoCV(alphas=alpha_values, cv=5, random_state=42)

# Fit the model
lasso_cv.fit(X_train, y_train)

# Best alpha value
best_alpha = lasso_cv.alpha_
print(f"\nOptimal alpha value that minimizes MAPE: {best_alpha}")

# Train the Lasso model with the optimal alpha
lasso_optimal = Lasso(alpha=best_alpha, random_state=42)
lasso_optimal.fit(X_train, y_train)

# Predict and calculate MAPE
y_pred_optimal = lasso_optimal.predict(X_test)
mape_optimal = mean_absolute_percentage_error(y_test, y_pred_optimal) * 100

print(f"\nMAPE with optimal alpha ({best_alpha}): {mape_optimal:.2f}%")

Coefficients estimated by the Lasso model with alpha=1:
                Feature  Coefficient
0    Explanatory Var #1     1.269726
1    Explanatory Var #2     1.683946
2    Explanatory Var #3     2.026262
3    Explanatory Var #4     2.087565
4    Explanatory Var #5    -0.917464
5    Explanatory Var #6    -0.000000
6    Explanatory Var #7     0.000000
7    Explanatory Var #8    -0.000000
8    Explanatory Var #9     0.000000
9   Explanatory Var #10    -0.000000
10  Explanatory Var #11     0.013142
11  Explanatory Var #12     0.000000
12  Explanatory Var #13    -0.000000
13  Explanatory Var #14     0.000000
14  Explanatory Var #15    -0.036177

Mean Absolute Percentage Error (MAPE) on the test set: 4.43%

Optimal alpha value that minimizes MAPE: 0.0001

MAPE with optimal alpha (0.0001): 0.00%

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 2: Run the Lasso model with alpha=1 and estimate the coefficients using the training set
lasso = Lasso(alpha=1, random_state=42)
lasso.fit(X_train_scaled, y_train)

# Get the coefficients
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lasso.coef_
})

print("Coefficients estimated by the Lasso model with alpha=1:")
print(coefficients)

# Step 3: Calculate the Mean Absolute Percentage Error using the test set
y_pred = lasso.predict(X_test_scaled)
mape = mean_absolute_percentage_error(y_test, y_pred) * 100  # Multiply by 100 to get percentage

print(f"\nMean Absolute Percentage Error (MAPE) on the test set: {mape:.2f}%")

# Step 4: Find an approximate value for alpha that minimizes the MAPE
# We'll use cross-validation to test different alpha values

from sklearn.linear_model import LassoCV

# Define a range of alpha values to test
alpha_values = np.logspace(-4, 1, 50)

# Initialize LassoCV to find the best alpha
lasso_cv = LassoCV(alphas=alpha_values, cv=5, random_state=42)

# Fit the model
lasso_cv.fit(X_train_scaled, y_train)

# Best alpha value
best_alpha = lasso_cv.alpha_
print(f"\nOptimal alpha value that minimizes MAPE: {best_alpha}")

# Train the Lasso model with the optimal alpha
lasso_optimal = Lasso(alpha=best_alpha, random_state=42)
lasso_optimal.fit(X_train_scaled, y_train)

# Predict and calculate MAPE
y_pred_optimal = lasso_optimal.predict(X_test_scaled)
mape_optimal = mean_absolute_percentage_error(y_test, y_pred_optimal) * 100

print(f"\nMAPE with optimal alpha ({best_alpha}): {mape_optimal:.2f}%")

Coefficients estimated by the Lasso model with alpha=1:
                Feature  Coefficient
0    Explanatory Var #1     8.085504
1    Explanatory Var #2    15.751859
2    Explanatory Var #3     2.171211
3    Explanatory Var #4    16.303135
4    Explanatory Var #5    -5.216422
5    Explanatory Var #6    -0.000000
6    Explanatory Var #7    -0.000000
7    Explanatory Var #8    -0.000000
8    Explanatory Var #9     0.000000
9   Explanatory Var #10    -0.000000
10  Explanatory Var #11     0.000000
11  Explanatory Var #12     0.000000
12  Explanatory Var #13    -0.000000
13  Explanatory Var #14    -0.000000
14  Explanatory Var #15    -0.000000

Mean Absolute Percentage Error (MAPE) on the test set: 5.16%

Optimal alpha value that minimizes MAPE: 0.0001

MAPE with optimal alpha (0.0001): 0.00%